Make Torch an optional dependency
trailofbits/fickling pull request #95
Opened 2024-03-01 16:59 UTC by suhacker1

2024-03-01 17:43 UTC, suhacker1 commented
Since PyTorch is now an optional dependency, we should update the installation instructions in the README when the new version is out.

2024-03-03 15:12 UTC, Boyan-MILANOV requested changes

2024-03-03 15:12 UTC, Boyan-MILANOV commented on fickling/pytorch.py
> +        "Please use pip install '.[torch]'"
Shouldn't this be `pip install fickling[torch]`? I'm assuming people won't install by cloning the repo but do it from PyPI directly so `.[torch]` doesn't apply to them.

2024-03-03 15:12 UTC, Boyan-MILANOV commented on README.md
As per your comment in the PR discussions, I think you should update the README with the new install instructions in this PR already. They go together.

If we don't want to have this pushed to `master` before a new release is out then it's perhaps time to have a `dev` working branch and use `master` only for releases. In fact I think we should do it anyway if we keep developing new `fickling` features

2024-03-03 22:22 UTC, suhacker1 commented on README.md
That makes sense. I'll add this and merge this PR right before making a new release then to make this easier in this case. But we can discuss the `dev` branch later.

2024-03-04 10:23 UTC, Boyan-MILANOV approved these changes
LGTM!

2024-03-07 17:03 UTC, merged

2024-03-20 14:10 UTC, drdavella commented
Hi! We appreciate the work you're doing and especially this change to make Torch and optional dependency. I was just curious whether there are any plans to release this change in the near future? Thank you!

2024-03-20 14:48 UTC, suhacker1 commented
Thanks for the reminder! We'll put out the new release very soon.

2024-03-26 19:29 UTC, suhacker1 commented
@drdavella We published the new release! Please don't hesitate to reach out with any issues or feature requests!